const express=require("express"),session=require("express-session"),multer=require("multer"),Database=require("better-sqlite3"),path=require("path"),fs=require("fs");
const app=express(),PORT=process.env.PORT||3000;
const db=new Database("property.db");
db.exec(`CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,type TEXT,purpose TEXT,location TEXT,price TEXT,phone TEXT,description TEXT,image TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);`);
const defaults={siteName:"NEXPROPERTY",tagline:"ယုံကြည်စိတ်ချရသော အိမ်ခြံမြေ",heroTitle:"သင့်အိပ်မက်အိမ်ကို",heroAccent:"ဒီမှာရှာပါ",heroText:"အိမ်၊ ခြံ၊ ကွန်ဒို၊ ဆိုင်ခန်းများကို လွယ်ကူမြန်ဆန်စွာ ရှာဖွေပါ။",phone:"09 123 456 789",address:"ရန်ကုန်",logo:"🏠",primaryColor:"#087a73"};
const setStmt=db.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)"); for(const [k,v] of Object.entries(defaults)) setStmt.run(k,v);
const count=db.prepare("SELECT COUNT(*) c FROM properties").get().c;
if(!count) db.prepare(`INSERT INTO properties(title,type,purpose,location,price,phone,description,image) VALUES(?,?,?,?,?,?,?,?)`).run("လှိုင် Family House","အိမ်","ရောင်း","လှိုင်၊ ရန်ကုန်","1,850 သိန်း","09 123 456 789","မိသားစုနေထိုင်ရန် အဆင်ပြေသော အိမ်။","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80");
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||"change-this-secret",resave:false,saveUninitialized:false,cookie:{maxAge:86400000}}));
app.use(express.static("public"));app.use("/uploads",express.static("uploads"));
const upload=multer({dest:"uploads/"});
const admin=(req,res,next)=>req.session.admin?next():res.status(401).json({error:"Unauthorized"});
app.get("/api/properties",(req,res)=>res.json(db.prepare("SELECT * FROM properties ORDER BY id DESC").all()));
app.get("/api/settings",(req,res)=>{const rows=db.prepare("SELECT key,value FROM settings").all();res.json(Object.fromEntries(rows.map(x=>[x.key,x.value])))});
app.put("/api/settings",admin,(req,res)=>{const stmt=db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value"); for(const k of Object.keys(defaults)) if(req.body[k]!==undefined) stmt.run(k,String(req.body[k])); res.json({ok:true})});
app.post("/api/login",(req,res)=>{if(req.body.username==="admin"&&req.body.password==="admin123"){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:"Login မအောင်မြင်ပါ"})});
app.post("/api/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/me",(req,res)=>res.json({admin:!!req.session.admin}));
app.post("/api/properties",admin,upload.single("image"),(req,res)=>{let image=req.body.image||"";if(req.file) image="/uploads/"+req.file.filename;const r=db.prepare(`INSERT INTO properties(title,type,purpose,location,price,phone,description,image) VALUES(?,?,?,?,?,?,?,?)`).run(req.body.title,req.body.type,req.body.purpose,req.body.location,req.body.price,req.body.phone,req.body.description,image);res.json({id:r.lastInsertRowid})});
app.put("/api/properties/:id",admin,upload.single("image"),(req,res)=>{let p=db.prepare("SELECT * FROM properties WHERE id=?").get(req.params.id);let image=p.image;if(req.file) image="/uploads/"+req.file.filename;else if(req.body.image!==undefined) image=req.body.image;db.prepare(`UPDATE properties SET title=?,type=?,purpose=?,location=?,price=?,phone=?,description=?,image=? WHERE id=?`).run(req.body.title,req.body.type,req.body.purpose,req.body.location,req.body.price,req.body.phone,req.body.description,image,req.params.id);res.json({ok:true})});
app.delete("/api/properties/:id",admin,(req,res)=>{db.prepare("DELETE FROM properties WHERE id=?").run(req.params.id);res.json({ok:true})});
app.listen(PORT,()=>console.log("NEXPROPERTY running on http://localhost:"+PORT));